FROM rust
WORKDIR /usr/local/src/vector-db-proxy
RUN mkdir -p src
COPY Cargo.toml .
COPY Cargo.lock .
COPY . .
RUN cargo build

# TODO: make this work for all architectures
RUN mkdir /onnxruntime \
	&& cd /onnxruntime \
	&& wget https://github.com/microsoft/onnxruntime/releases/download/v1.17.1/onnxruntime-linux-x64-1.17.1.tgz \
	&& tar -xvf onnxruntime-linux-x64-1.17.1.tgz \
	&& cd onnxruntime-linux-x64-1.17.1 \
	&& cp lib/libonnxruntime.so.1.17.1 /lib \
	&& cp lib/libonnxruntime.so.1.17.1 /usr/lib

EXPOSE 8001
CMD ["target/debug/vector-db-proxy"]
