'use strict';

const SecretKeys = {
	AMAZON_ACCESS_ID: 'AMAZON_ACCESS_ID', //'RAPTOR_APP_AMAZON_ACCESSKEYID',
	AMAZON_SECRET_ACCESS_KEY: 'AMAZON_SECRET_ACCESS_KEY', //'RAPTOR_APP_AMAZON_SECRETACCESSKEY',
};

export default SecretKeys;
